### ISSUE TITLE
Output file

### ISSUE THREAD

**Issue by RobboRob** [cedric-r/HomeMade.SkyModel#2]
Where do you dump the outpuit of the sky model. is there an output file and where is it positioned on the harddisk?

**Comment by cedric-r** [comment]
Hi there.
I don't create an output file. What the software does is plate solve and send corrections to eqmod. Nothing is saved. It's entirely eqmod that creates the model internally. Once eqmod has a model, it can be saved to disk, but you'll need a working eqmod for your mount to get there.
